### ISSUE TITLE
Add comma seperator at thousand marks when entering scores

### ISSUE THREAD

**Issue by davidrs** [scottwainstock/pbm#1241] opened 2020-03-13 20:46 UTC
When entering and viewing high scores it would be helpful if the text field displayed ',' between the thousand marks.

`9,000,000` instead of `9000000`

Will make it easier to enter scores correctly and quickly skim others scores.

If I have some time I'm happy to take a try and this fix.

**Comment by RyanTG** [comment] 2020-03-13 21:02
![Screenshot_20200313_140206](https://user-images.githubusercontent.com/632682/76659271-2fecb180-6533-11ea-9d39-13fff0a72210.png)

It does display the commas. Where are you not seeing the commas?

**Comment by davidrs** [comment] 2020-03-13 21:17
Entering the score is where I really felt the need for it, but I also noticed it in the feed. (Forgot to mention I'm on Android, mobile app)

![Screenshot_20200313-141426](https://user-images.githubusercontent.com/1407489/76660023-33813800-6535-11ea-8434-43d5a741742c.png)
![Screenshot_20200313-141500](https://user-images.githubusercontent.com/1407489/76660026-367c2880-6535-11ea-80e3-f52b9007febe.png)

**Comment by RyanTG** [comment] 2020-03-13 21:33
Ah, gotcha. This is a good issue.

But, this github project is just for the website. We have a separate project for the app: https://github.com/bpoore/pbm-react

Can you create the issue on that project? I'll update the readme on this project to make that more clear.

**Comment by davidrs** [comment] 2020-03-13 21:34
oops, thanks @RyanTG  I'd found the right repo last night and then opened the wrong one this afternoon 🙃

**Comment by RyanTG** [comment] 2020-03-17 04:39
Reopening, because this is partially a website issue. 

the recent activity stream comes straight from the api as a string. We’d have to add the delimiter to the score: https://github.com/scottwainstock/pbm/blob/f5cd2a4960166865faf9ea7b3379d9acf7c2d7c3/app/models/machine_score_xref.rb#L29

I’ll dig into it. But maybe like: https://github.com/scottwainstock/pbm/blob/11eb2445f2a712d195ca0b0fb61a43940aa6a249/app/views/users/profile.html.haml#L57

**Comment by RyanTG** [comment] 2020-03-17 05:42
This should do it: https://github.com/scottwainstock/pbm/pull/1237/commits/caa6daf888c0c0a63df7324302394e09df94a1e0

Once merged, this will show up on the app without any app update.

**Comment by RyanTG** [comment] 2020-03-17 06:18
I didn't see an obvious solution to formatting _while_ typing. @bpoore thoughts?

**Comment by bpoore** [comment] 2020-03-17 18:38
Something like this? https://stackoverflow.com/questions/46516136/comma-separated-step-for-number-input-box

**Comment by RyanTG** [comment] 2020-03-17 22:49
augh, I meant to tag you on the https://github.com/bpoore/pbm-react/issues/293 issue, not the pbm one. oops! I'll continue the convo there.

**Comment by RyanTG** [comment] 2020-03-19 04:30
@davidrs It’s merged now. So newly-added scores will show commas in the Recent Activity feed. People aren’t really updating the map right now, though!

**Comment by RyanTG** [comment] 2020-03-21 22:56
@bpoore I’m testing this out on the website, and it works (commas appear when typing). Except it doesn’t submit, because now the string contains invalid characters. I wonder if we’d then have to strip them out on submit? Might have the same issue on the app. Maybe @scottwainstock has an idea.

**Comment by bpoore** [comment] 2020-03-22 04:34
With what I was going to do for the app, we won't have that problem. We can look into what to do for the site!

**Comment by bpoore** [comment] 2020-03-22 19:49
I did end up needing to strip the commas for the app as well. My original plan was to show the user a value with commas, but not actually add them... was easier to just add them, then remove them. Here is regex for stripping commas: https://github.com/bpoore/pbm-react/commit/d9af3afee191149b89be9672ce5f424485bb53f9#diff-0bdb243de7529a374b26afe055a33b9dR26

**Comment by RyanTG** [comment] 2020-03-22 20:15
Thanks. I was attempting to do something similar to that regex. The problem is that the form seems to check for validation BEFORE anything is submitted. I'm having trouble stripping out the commas prior to the validation. It's not clear yet where in the code this validation check is specified. But... I've only had a couple minutes here and there to dig in to it.

**Comment by RyanTG** [comment] 2020-03-23 04:43
Nevermind. It was actually `pattern="^[\d,]+$"` from the example that was messing up the validation. I think I got this now.

**Comment by RyanTG** [comment] 2020-03-23 05:53
Adds commas to input form: https://github.com/scottwainstock/pbm/pull/1242

**Closed** 2020-10-07 16:12 UTC
